[project]
name = "phising-detect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.5.3",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
]
